services:
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - microblogging-network
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=microblogging
    volumes:
      - ./.database/:/data/db/
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    networks:
      - microblogging-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - '8081:8081'
    volumes:
      - ./.database:/data/db

networks:
  microblogging-network:
    driver: bridge